
<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


### 1. Todas las empresas cuyo nombre sea 'Babelgum'. Recupera solo su campo `name`.
### 2. Todas las empresas que tienen más de 5000 empleados. Limita la búsqueda a 20 empresas y ordénalas por **número de empleados**.
### 3. Todas las empresas fundadas entre 2000 y 2005, incluyendo ambos años. Recupera solo los campos `name` y `founded_year`.
### 4. Todas las empresas que tuvieron una valoración de más de 100.000.000 y que fueron fundadas antes de 2010. Recupera solo los campos `name` e `ipo`.
### 5. Todas las empresas que tienen menos de 1000 empleados y que fueron fundadas antes de 2005. Ordénalas por el número de empleados y limita la búsqueda a 10 empresas.
### 6. Todas las empresas que no incluyen el campo `partners`.
### 7. Todas las empresas que tienen un valor nulo en el campo `category_code`.
### 8. Todas las empresas que tienen al menos 100 empleados pero menos de 1000. Recupera solo los campos `name` y `number of employees`.
### 9. Ordena todas las empresas por su precio de IPO en orden descendente.
### 10. Recupera las 10 empresas con más empleados, ordenadas por el `número de empleados`.
### 11. Todas las empresas fundadas en el segundo semestre del año. Limita tu búsqueda a 1000 empresas.
### 12. Todas las empresas fundadas antes del año 2000 que tienen un monto de adquisición superior a 10.000.000.
### 13. Todas las empresas que han sido adquiridas después de 2010, ordénalas por el monto de adquisición, y recupera solo los campos `name` y `acquisition`.
### 14. Ordena las empresas por su `founded year`, recuperando solo los campos `name` y `founded year`.
### 15. Todas las empresas que han sido fundadas en los primeros siete días del mes, incluyendo el séptimo. Ordénalas por su `acquisition price` en orden descendente. Limita la búsqueda a 10 documentos.
### 16. Todas las empresas en la categoría 'web' que tienen más de 4000 empleados. Ordénalas por la cantidad de empleados en orden ascendente.
### 17. Todas las empresas cuyo monto de adquisición es superior a 10.000.000, y cuya moneda es 'EUR'.
### 18. Todas las empresas que han sido adquiridas en el primer trimestre del año. Limita la búsqueda a 10 empresas, y recupera solo los campos `name` y `acquisition`.

In [2]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Para trabajar con datos de tipo fecha
# ------------------------------------------------------------------------------
from datetime import datetime

# Para trabajar con Mongo
# ------------------------------------------------------------------------------
import pymongo

# Para utilizar nuestras funciones
# ------------------------------------------------------------------------------
#from src import soporte_mongo as sm

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [3]:
# lo primero que tenemos que hacer es conectarnos con Mongo
cliente = pymongo.MongoClient()
print(cliente)

# como la conexión se ha realizado con éxito vamos a ver las bases de datos que tenemos
cliente.list_database_names()

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

['Airbnb', 'Ecommerce', 'admin', 'config', 'local']

In [4]:
# nos conectamos con una BBDD 
ecommerce = cliente['Ecommerce']

#Veamos además las colecciones de la BBDD, usando el método 'list_collection_names()'
ecommerce.list_collection_names()

['Compagnies']

In [5]:
compagnies = ecommerce['Compagnies']

In [6]:
compagnies_df = pd.DataFrame(compagnies.find())

In [7]:
compagnies_df.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,2005.0,10.0,17.0,1.0,"wiki, seattle, elowitz, media-industry, media-...",,info@wetpaint.com,206.859.6300,Technology Platform Company,2007-05-25 06:51:27,Sun Dec 08 07:15:44 UTC 2013,<p>Wetpaint is a technology platform company t...,"{'available_sizes': [[[150, 75], 'assets/image...","[{'name': 'Wikison Wetpaint', 'permalink': 'we...","[{'is_past': False, 'title': 'Co-Founder and V...","[{'competitor': {'name': 'Wikia', 'permalink':...",[],$39.8M,"[{'id': 888, 'round_code': 'a', 'source_url': ...",[],"{'price_amount': 30000000, 'price_currency_cod...",[],"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8b,AdventNet,abc3,http://www.crunchbase.com/company/adventnet,http://adventnet.com,,,manageengine,enterprise,600.0,1996.0,NaN,NaN,2.0,,Zoho ManageEngine,pr@adventnet.com,925-924-9500,Server Management Software,2007-05-25 19:24:22,Wed Oct 31 18:26:09 UTC 2012,"<p>AdventNet is now <a href=""/company/zoho-man...","{'available_sizes': [[[150, 55], 'assets/image...",[],"[{'is_past': True, 'title': 'CEO and Co-Founde...",[],"[{'title': 'DHFH', 'is_past': True, 'provider'...",$0,[],[],None,[],"[{'description': 'Headquarters', 'address1': '...",[],[],"[{'available_sizes': [[[150, 94], 'assets/imag...",[],[],NaN,NaN,NaN,NaN

In [8]:
### 1. Todas las empresas cuyo nombre sea 'Babelgum'. Recupera solo su campo `name`.


babelgum_df =  pd.DataFrame(compagnies.find({'name': 'Babelgum'}))


print(f"Las empresas que tenemos son: {babelgum_df['name'].unique()} ")
print(f"El número total es {babelgum_df.shape[0]}")

Las empresas que tenemos son: ['Babelgum']
El número total es 1

In [23]:
### 2. Todas las empresas que tienen más de 5000 empleados. Limita la búsqueda a 20 empresas y ordénalas por **número de empleados**.
mayor_que1 = pd.DataFrame(compagnies.find(
    {'number_of_employees': {"$gt": 5000}})
    .limit(20)
    .sort({"number_of_employees":1}))
mayor_que1.head(2)

print(f"Hay {len(mayor_que1)} empresas con más de 5k empleados.")

Hay 20 empresas con más de 5k empleados.

In [26]:
### 3. Todas las empresas fundadas entre 2000 y 2005, incluyendo ambos años. Recupera solo los campos `name` y `founded_year`.

rango_founded = pd.DataFrame(compagnies.find({
    "$and": [
        {"founded_year": {"$gte": 2000}},
        {"founded_year": {"$lte": 2005}}]},
        {'name':1, 'founded_year':1}))
rango_founded.head(2)

print(f"Hay {len(rango_founded)} fundadas empresas entre 2000 y 2005")

Hay 3734 fundadas empresas entre 2000 y 2005

In [11]:
### 4. Todas las empresas que tuvieron una valoración de más de 100.000.000 y que fueron fundadas antes de 2010. Recupera solo los campos `name` e `ipo`.
                        
valoracion = pd.DataFrame(compagnies.find({
    "$and": [
        {'ipo.valuation_amount': {"$gt": 100000}},
        {"founded_year": {"$lt": 2010}}
    ]}))
valoracion.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004,2.0,1.0,None,None,None,,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,Thu Nov 21 19:40:55 UTC 2013,<p>Facebook is the world&#8217;s largest socia...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Facebook Platform', 'permalink': 'f...","[{'is_past': False, 'title': 'Founder and CEO,...","[{'competitor': {'name': 'MySpace', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$2.43B,"[{'id': 2, 'round_code': 'angel', 'source_url'...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]
1,52cdef7c4bab8bd675297d94,Twitter,twitter,http://www.crunchbase.com/company/twitter,http://twitter.com,http://twitter.com/blog,http://feeds.feedburner.com/TwitterBlog,twitter,social,1300.0,2006,3.0,21.0,None,None,None,,"text, messaging, social, community, twitter, t...",,press@twitter.com,,Real time communication platform,Fri Jun 01 08:42:34 UTC 2007,Sat Dec 07 16:07:56 UTC 2013,"<p>Created in 2006, Twitter is a global real-t...","{'available_sizes': [[[150, 150], 'assets/imag...","[{'name': 'Twitter Blocks', 'permalink': 'twit...","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Digg', 'permalink': ...","[{'title': 'Hosting', 'is_past': True, 'provid...",$1.16B,"[{'id': 261, 'round_code': 'a', 'source_url': ...",[],None,"[{'price_amount': 15000000, 'price_currency_co...","[{'description': '', 'address1': '1355 Market ...","[{'id': 1, 'description': 'Survives iPhone 3G ...","{'valuation_amount': 18100000000, 'valuation_c...","[{'embed_code': '<iframe width=""430"" height=""2...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://sec.gov/cgi-bin/brow...,[]

In [27]:
### 5. Todas las empresas que tienen menos de 1000 empleados y que fueron fundadas antes de 2005. Ordénalas por el número de empleados y limita la búsqueda a 10 empresas.

empleados_fundacion = pd.DataFrame(compagnies.find({
    "$and": [
        {'number_of_employees': {"$lt": 1000}},
        {"founded_year": {"$lt": 2010}}
    ]})
    .limit(10)
    .sort({"number_of_employees":1}))

empleados_fundacion.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297dbc,Skype,skype,http://www.crunchbase.com/company/skype,http://www.skype.com,http://blogs.skype.com,http://feeds.feedburner.com/shareskypeen,skype,software,0,2003,8.0,NaN,NaN,NaN,NaN,,"phone, voip, sweden, skype",,,94117733,VoIP Software,Tue Jul 03 05:20:31 UTC 2007,Wed Dec 11 13:03:57 UTC 2013,<p>Skype is a software application that allows...,"{'available_sizes': [[[150, 66], 'assets/image...","[{'name': 'Skype', 'permalink': 'skype'}, {'na...","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'fring Ltd', 'permali...","[{'title': '', 'is_past': False, 'provider': {...",$76.8M,"[{'id': 79, 'round_code': 'b', 'source_url': '...","[{'funding_round': {'round_code': 'a', 'source...","{'price_amount': 2600000000, 'price_currency_c...","[{'price_amount': 150000000, 'price_currency_c...","[{'description': 'Global HQ', 'address1': '23-...","[{'id': 552, 'description': 'Skype released pu...",None,"[{'embed_code': '<iframe src=""http://blip.tv/p...","[{'available_sizes': [[[150, 130], 'assets/ima...",[{'external_url': 'http://www.ewdn.com/2011/06...,[]
1,52cdef7c4bab8bd675297d9d,Joost,joost,http://www.crunchbase.com/company/joost,http://joost.com,http://blog.joost.com,http://blog.joost.com/atom.xml,None,games_video,0,2006,10.0,1.0,NaN,NaN,NaN,None,"iptv, babelgum, television, video, thevenicepr...",None,newyork@joost.com,,None,Sat Jun 09 07:05:30 UTC 2007,Fri Mar 15 23:31:11 UTC 2013,"<p>As their third major undertaking, <a href=""...","{'available_sizes': [[[150, 64], 'assets/image...","[{'name': 'Joost', 'permalink': 'joost'}]","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Babelgum', 'permalin...",[],$45M,"[{'id': 19, 'round_code': 'a', 'source_url': '...",[],"{'price_amount': None, 'price_currency_code': ...",[],"[{'description': '', 'address1': '100 5th Ave ...","[{'id': 4860, 'description': 'Joost Video Netw...",None,"[{'embed_code': '<object width=""425"" height=""3...",[],[],[]

In [13]:
### 6. Todas las empresas que no incluyen el campo `partners`.
partner = pd.DataFrame(compagnies.find({
    'partners' :{'exists': False}
}))

partner

Empty DataFrame
Columns: []
Index: []

In [32]:
### 7. Todas las empresas que tienen un valor nulo en el campo `category_code`.

category_nulo = pd.DataFrame(compagnies.find({
    "category_code":{"$eq":None}
}))

category_nulo.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd6752980f6,Collective,collective,http://www.crunchbase.com/company/collective,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,Thu Sep 26 13:15:02 UTC 2013,Thu Sep 26 13:15:02 UTC 2013,None,None,[],[],[],[],$0,[],[],None,[],[],[],None,[],[],[],[]
1,52cdef7c4bab8bd675298225,Snimmer,snimmer,http://www.crunchbase.com/company/snimmer,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,Sat Feb 09 20:35:27 UTC 2008,Mon Mar 10 01:30:14 UTC 2008,None,None,[],[],[],[],$0,[],[],None,[],[],[],None,[],[],[],[]

In [15]:
### 8. Todas las empresas que tienen al menos 100 empleados pero menos de 1000. Recupera solo los campos `name` y `number of employees`.

empleados_rango = pd.DataFrame(compagnies.find({
    "$and": [
        {'number_of_employees': {"$gte": 100}},
        {"number_of_employees": {"$lte": 1000}}]},
        {"name": 1, "number_of_employees": 1}
    
    ))

empleados_rango.head(2)

                        _id       name  number_of_employees
0  52cdef7c4bab8bd675297d8b  AdventNet                  600
1  52cdef7c4bab8bd675297da7    AddThis                  120

In [33]:
### 9. Ordena todas las empresas por su precio de IPO en orden descendente.

precio_ipo = pd.DataFrame(compagnies.find()
                          .sort({'ipo.valuation_amount':-1}
                                ))

precio_ipo.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7e4bab8bd67529a8b4,GREE,gree,http://www.crunchbase.com/company/gree,http://www.gree-corp.com,,,gree_corp,games_video,700.0,2004.0,12.0,7.0,NaN,NaN,NaN,None,"mobile-web, japan, tokyo, social-network, mobi...",None,inquiry@gree-corp.com,,"Internet media business,SNS, free game",Sat Dec 20 16:42:57 UTC 2008,Tue Jan 01 21:37:04 UTC 2013,<p>GREE provides Japan&#8217;s leading mobile ...,"{'available_sizes': [[[150, 61], 'assets/image...",[],"[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Mobage-town', 'perma...",[],¥464M,"[{'id': 18872, 'round_code': 'unattributed', '...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': 104000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 1021, 'description': 'IPO', 'stoned_ye...","{'valuation_amount': 108960000000, 'valuation_...",[],"[{'available_sizes': [[[133, 150], 'assets/ima...",[],[]
1,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,2.0,1.0,NaN,NaN,NaN,,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,Thu Nov 21 19:40:55 UTC 2013,<p>Facebook is the world&#8217;s largest socia...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Facebook Platform', 'permalink': 'f...","[{'is_past': False, 'title': 'Founder and CEO,...","[{'competitor': {'name': 'MySpace', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$2.43B,"[{'id': 2, 'round_code': 'angel', 'source_url'...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]

In [34]:
### 10. Recupera las 10 empresas con más empleados, ordenadas por el `número de empleados`.

empresas10 = pd.DataFrame(compagnies.find()
                          .sort({'number_of_employees':-1})
                          .limit(10)
                          )

empresas10.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd67529941a,Siemens,siemens,http://www.crunchbase.com/company/siemens,http://www.siemens.com,,,Siemens,hardware,405000,1847,NaN,NaN,None,None,None,None,"automation, building-technologies, drive-techn...",,contact@siemens.com,49 89 636 34134,Electronics and Electrical Engineering,Thu Jul 31 09:29:43 UTC 2008,Thu Nov 28 20:32:55 UTC 2013,"<p>Siemens AG, an electronics and electrical e...","{'available_sizes': [[[150, 34], 'assets/image...",[],"[{'is_past': False, 'title': 'Chairman, Superv...",[],"[{'title': 'Application Development', 'is_past...",$8.9M,"[{'id': 17062, 'round_code': 'grant', 'source_...",[],None,"[{'price_amount': 418000000, 'price_currency_c...","[{'description': '', 'address1': 'Wittelsbache...","[{'id': 35852, 'description': 'Siemens Receive...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""420"" height=""3...","[{'available_sizes': [[[150, 92], 'assets/imag...",[],[]
1,52cdef7c4bab8bd67529856a,IBM,ibm,http://www.crunchbase.com/company/ibm,http://www.ibm.com,,,IBM,software,388000,1896,NaN,NaN,None,None,None,,,,ews@us.ibm.com,914-499-1900,,Fri Mar 14 22:55:52 UTC 2008,Sat Jan 04 02:56:24 UTC 2014,"<p>IBM, acronym for International Business Mac...","{'available_sizes': [[[150, 60], 'assets/image...","[{'name': 'Lotus Notes', 'permalink': 'lotus-n...","[{'is_past': False, 'title': 'Chairman of the ...","[{'competitor': {'name': 'BEA Systems', 'perma...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 10471, 'description': 'IBM Completes A...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...","[{'external_url': 'http://mashpedia.com/IBM', ...",[]

In [35]:
### 11. Todas las empresas fundadas en el segundo semestre del año. Limita tu búsqueda a 1000 empresas.

empresas_seg_semestre = pd.DataFrame(compagnies.find({
    'founded_month': {"$gte": 6},
    'founded_month':{"$ne":None}}) #puedo quitar los none
    .limit(1000))

empresas_seg_semestre.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,2005,10,17.0,1.0,"wiki, seattle, elowitz, media-industry, media-...",,info@wetpaint.com,206.859.6300,Technology Platform Company,2007-05-25 06:51:27,Sun Dec 08 07:15:44 UTC 2013,<p>Wetpaint is a technology platform company t...,"{'available_sizes': [[[150, 75], 'assets/image...","[{'name': 'Wikison Wetpaint', 'permalink': 'we...","[{'is_past': False, 'title': 'Co-Founder and V...","[{'competitor': {'name': 'Wikia', 'permalink':...",[],$39.8M,"[{'id': 888, 'round_code': 'a', 'source_url': ...",[],"{'price_amount': 30000000, 'price_currency_cod...",[],"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8c,Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,2005,9,15.0,3.0,"zoho, officesuite, spreadsheet, writer, projec...",,info@zohocorp.com,1-888-204-3539,Online Business Apps Suite,Fri May 25 19:30:28 UTC 2007,Wed Oct 30 00:07:05 UTC 2013,"<p>Zoho offers a suite of Business, Collaborat...","{'available_sizes': [[[150, 55], 'assets/image...","[{'name': 'Zoho Office Suite', 'permalink': 'z...","[{'is_past': False, 'title': 'CEO and Founder'...","[{'competitor': {'name': 'Empressr', 'permalin...",[],$0,[],[],None,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],NaN,NaN,NaN,NaN

In [36]:
### 12. Todas las empresas fundadas antes del año 2000 que tienen un monto de adquisición superior a 10.000.000.

adquisicion_fundacion = pd.DataFrame(compagnies.find({
    "$and": [
        {"acquisition.price_amount": {"$gt": 10000000}},
        {"founded_year": {"$lt": 2000}}
    ]}))

adquisicion_fundacion.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297d90,Postini,postini,http://www.crunchbase.com/company/postini,http://postini.com,,,None,web,NaN,1999,6.0,2.0,NaN,NaN,NaN,None,,None,,888.584.3150,None,Fri Jun 08 12:19:51 UTC 2007,Sat Aug 13 18:02:34 UTC 2011,<p>Postini focuses on two main issues: securit...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Postini Solutions', 'permalink': 'p...","[{'is_past': False, 'title': 'Board', 'person'...","[{'competitor': {'name': 'RescueTime', 'permal...",[],$0,[],[],"{'price_amount': 625000000, 'price_currency_co...",[],"[{'description': None, 'address1': '959 Skyway...",[],None,[],[],[],[]
1,52cdef7c4bab8bd675297deb,SideStep,sidestep,http://www.crunchbase.com/company/sidestep,http://www.sidestep.com,None,None,None,web,75.0,1999,11.0,1.0,NaN,NaN,NaN,None,"deals, travel, flights, hotels, tickets, vacat...",None,None,408-235-1700,None,Wed Jul 11 02:50:10 UTC 2007,Thu Jan 13 02:41:17 UTC 2011,<p>SideStep is a metasearch engine for travel ...,"{'available_sizes': [[[150, 52], 'assets/image...","[{'name': 'SideStep', 'permalink': 'sidestep'}]","[{'is_past': False, 'title': 'Board', 'person'...","[{'competitor': {'name': 'Mobissimo', 'permali...",[],$32M,"[{'id': 105, 'round_code': 'c', 'source_url': ...",[],"{'price_amount': 180000000, 'price_currency_co...",[],"[{'description': None, 'address1': '2980 Bower...",[],None,[],[],[],[]

In [38]:
### 13. Todas las empresas que han sido adquiridas después de 2010, ordénalas por el monto de adquisición, y recupera solo los campos `name` y `acquisition`.

empresas_ano_monto = pd.DataFrame(compagnies.find({
    'acquisition.acquired_year': {"$gte": 2010}},
    {"name": 1, "acquisition": 1})
    .sort({'acquistion.price_amount':1}
           ))

empresas_ano_monto.head(2)

,_id,name,acquisition
0,52cdef7c4bab8bd675297d8a,Wetpaint,"{'price_amount': 30000000, 'price_currency_cod..."
1,52cdef7c4bab8bd675297d8d,Digg,"{'price_amount': 500000, 'price_currency_code'..."

In [52]:
### 14. Ordena las empresas por su `founded year`, recuperando solo los campos `name` y `founded year`.

empresas_founded = pd.DataFrame(compagnies.find(
    {"founded_year": {"$ne":None}},
    {"name":1, "founded_year":1})
    .sort({"founded_year":-1}))

empresas_founded.head(2)

                        _id    name  founded_year
0  52cdef7d4bab8bd675298ea7  iBazar          2013
1  52cdef7e4bab8bd67529a3b8  Clowdy          2013

In [47]:
### 15. Todas las empresas que han sido fundadas en los primeros siete días del mes, incluyendo el séptimo. Ordénalas por su `acquisition price` en orden descendente. Limita la búsqueda a 10 documentos.

primeros_dias = pd.DataFrame(compagnies.find(
    {"founded_day": {"$in":[1,2,3,4,5,6,7]}})
    .sort({"acquisition.price_amount":-1})
    .limit(10))

primeros_dias.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd6752989a1,Netscape,netscape,http://www.crunchbase.com/company/netscape,http://netscape.aol.com,,,,software,NaN,1994,4,4,NaN,NaN,NaN,None,None,,,,,Tue May 06 00:27:28 UTC 2008,Thu Nov 14 00:57:06 UTC 2013,<p>Netscape Communications Corporation offers ...,"{'available_sizes': [[[150, 40], 'assets/image...",[],"[{'is_past': False, 'title': 'Chief Scientist'...",[],[],$0,"[{'id': 20468, 'round_code': 'c', 'source_url'...",[],"{'price_amount': 4200000000, 'price_currency_c...",[],"[{'description': '', 'address1': '466 Ellis St...",[],None,[],[],[],[]
1,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000.0,1998,12,1,NaN,NaN,NaN,None,"moneytransfer, crunchbase, ecommerce, paypal, ...",,,207-619-2873,Internet payment service,Wed Aug 01 09:16:46 UTC 2007,Fri Dec 20 04:43:53 UTC 2013,<p>PayPal is an online payments and money tran...,"{'available_sizes': [[[150, 51], 'assets/image...","[{'name': 'PayPal Here', 'permalink': 'paypal-...","[{'is_past': False, 'title': 'Vice President, ...","[{'competitor': {'name': 'KushCash', 'permalin...","[{'title': 'Public Relations', 'is_past': True...",$197M,"[{'id': 284, 'round_code': 'd', 'source_url': ...","[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]

In [46]:
### 16. Todas las empresas en la categoría 'web' que tienen más de 4000 empleados. Ordénalas por la cantidad de empleados en orden ascendente.

# Por defecto, con 2 condiciones se aplicará un $and

empresas_web = pd.DataFrame(compagnies.find({
        'category_code': {"$eq": "web"},
        "number_of_employees": {"$gte": 4000}})
        .sort({"number_of_employees":1}))

empresas_web.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd67529822a,Expedia,expedia,http://www.crunchbase.com/company/expedia,http://www.expedia.com,,,Expedia,web,4400,1996,NaN,NaN,None,None,None,None,"travel, flights, hotels, tickets, airline, vac...",,,1-800-EXPEDIA,,Sun Feb 10 03:29:12 UTC 2008,Sun Dec 08 07:03:33 UTC 2013,<p>Expedia.com is an Internet-based travel age...,"{'available_sizes': [[[150, 115], 'assets/imag...",[],"[{'is_past': False, 'title': 'Director and Vic...","[{'competitor': {'name': 'Farecast', 'permalin...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': None, 'price_currency_code': ...","[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Office', 'address1...","[{'id': 11691, 'description': 'US AIRWAYS AND ...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 93], 'assets/imag...",[{'external_url': 'http://www.urlaubs-rabatte....,[]
1,52cdef7c4bab8bd675297e96,AOL,aol,http://www.crunchbase.com/company/aol,http://www.aol.com,http://blog.aol.com/,http://feeds.feedburner.com/AolBlog?format=xml,aol,web,8000,1985,5.0,24.0,None,None,None,,"american-on-line, america-online","America Online, America on-line",,+1-703-265-1000,,Fri Aug 03 06:26:04 UTC 2007,Fri Nov 29 21:51:48 UTC 2013,<p>AOL is a global advertising-supported Web c...,"{'available_sizes': [[[150, 84], 'assets/image...","[{'name': 'Xdrive', 'permalink': 'xdrive'}, {'...","[{'is_past': False, 'title': 'CEO, Chairman', ...","[{'competitor': {'name': 'MySpace', 'permalink...",[],$1B,"[{'id': 3548, 'round_code': 'post_ipo_equity',...","[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 40000000, 'price_currency_co...","[{'description': 'HQ', 'address1': '770 Broadw...","[{'id': 2689, 'description': 'AOL relauches, c...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 91], 'assets/imag...","[{'external_url': 'http://mashpedia.com/AOL', ...",[]

In [49]:
### 17. Todas las empresas cuyo monto de adquisición es superior a 10.000.000, y cuya moneda es 'EUR'.

empresas_eur = pd.DataFrame(compagnies.find({
        'acquisition.price_currency_code': {"$eq": "EUR"},
        "acquisition.price_amount": {"$gt": 10000000}}))

empresas_eur.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297f02,ZYB,zyb,http://www.crunchbase.com/company/zyb,http://zyb.com,http://blog.zyb.com/,http://blog.zyb.com/index.php/feed/,None,mobile,25.0,NaN,NaN,NaN,None,None,None,None,"mobile, social-networking, socialnetwork",,contact@zyb.com,,Mobile Social Networking,Wed Aug 22 05:14:51 UTC 2007,Tue Jul 02 03:00:50 UTC 2013,<p>ZYB is a mobile phone utility and social ne...,"{'available_sizes': [[[32, 32], 'assets/images...","[{'name': 'ZYB | Phone', 'permalink': 'zyb-pho...","[{'is_past': None, 'title': 'CEO and Co-Founde...","[{'competitor': {'name': 'Twitter', 'permalink...","[{'title': '', 'is_past': True, 'provider': {'...",€3M,"[{'id': 389, 'round_code': 'a', 'source_url': ...",[],"{'price_amount': 31500000, 'price_currency_cod...","[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': 'Esromgade ...",[],None,[],[],[],[]
1,52cdef7d4bab8bd675298bf3,Apertio,apertio,http://www.crunchbase.com/company/apertio,http://www.apertio.com,,,None,mobile,NaN,NaN,NaN,NaN,None,None,None,None,,None,,,None,Tue May 27 07:08:56 UTC 2008,Fri Aug 28 23:39:22 UTC 2009,"<p>Apertio One provides a single, open, subscr...","{'available_sizes': [[[150, 41], 'assets/image...",[],"[{'is_past': True, 'title': 'VP Business Devel...",[],[],$30M,"[{'id': 2405, 'round_code': 'b', 'source_url':...",[],"{'price_amount': 140000000, 'price_currency_co...",[],"[{'description': None, 'address1': '', 'addres...",[],None,[],[],[],[]

In [ ]:
### 18. Todas las empresas que han sido adquiridas en el primer trimestre del año. Limita la búsqueda a 10 empresas, y recupera solo los campos `name` y `acquisition`.

In [50]:
empresas_eur = pd.DataFrame(compagnies.find({
        'acquisition.acquired_month': {"$gte": 4}},
        {"name":1, "acquisition":1})
        .limit(10))

empresas_eur.head(2)

,_id,name,acquisition
0,52cdef7c4bab8bd675297d8a,Wetpaint,"{'price_amount': 30000000, 'price_currency_cod..."
1,52cdef7c4bab8bd675297d8d,Digg,"{'price_amount': 500000, 'price_currency_code'..."